generic_dict = {'generic_16Sm4Cm1402': ['BSU15140-MONOMER'],
                'generic_LYSINEaaRS': ['BSU00820-MONOMER'],
                'generic_Dus': ['BSU08030-MONOMER', 'BSU00810-MONOMER'],
                'generic_RF': ['BSU37010-MONOMER', 'BSU35290-MONOMER'],
                'generic_Tuf': ['BSU01130-MONOMER'],
                'generic_RNase': ['BSU23840-MONOMER','BSU16960-MONOMER',
                                  'BSU33610-MONOMER','BSU41050-MONOMER'],
                'generic_5s_rRNAs': ['BSU_RRNA_15', 'BSU_RRNA_11', 'BSU_RRNA_28',
                                      'BSU_RRNA_24', 'BSU_RRNA_18', 'BSU_RRNA_21',
                                      'BSU_RRNA_3', 'BSU_RRNA_13', 'BSU_RRNA_8',
                                      'BSU_RRNA_26'],
                'generic_16s_rRNAs': ['BSU_RRNA_4', 'BSU_RRNA_23', 'BSU_RRNA_16',
                                      'BSU_RRNA_6', 'BSU_RRNA_25', 'BSU_RRNA_1',
                                      'BSU_RRNA_22', 'BSU_RRNA_30', 'BSU_RRNA_9',
                                      'BSU_RRNA_19'],
                'generic_23s_rRNAs': ['BSU_RRNA_12', 'BSU_RRNA_7', 'BSU_RRNA_14',
                                     'BSU_RRNA_5', 'BSU_RRNA_2', 'BSU_RRNA_27',
                                     'BSU_RRNA_10', 'BSU_RRNA_17', 'BSU_RRNA_20',
                                     'BSU_RRNA_29']}
